language: node_js
services:
  - postgresql
node_js:
- '8'
before_install:
  npm install --save "follow-redirects@${FOLLOW_REDIRECTS_VERSION}"
env:
  - FOLLOW_REDIRECTS_VERSION=0.2.0
  - FOLLOW_REDIRECTS_VERSION=0.3.0
  - FOLLOW_REDIRECTS_VERSION=latest
